name: Test
on:
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check Formatting
        run: yarn format --check

      - name: Build mst-gql
        run: yarn build

      - name: Test mst-gql
        run: yarn test:mst-gql

      - name: Test Example 2 (Scaffolding)
        run: yarn test:example-2

      - name: Test Example 6 (Hasura)
        run: yarn test:example-6

#      - name: Test e2e vite app
#        run: yarn test:vite
